CREATE SCHEMA IF NOT EXISTS envers_audit;

CREATE TABLE IF NOT EXISTS envers_audit.revinfo
(
    rev integer GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 ),
    revtstmp bigint,
    CONSTRAINT revinfo_pkey PRIMARY KEY (rev)
);

CREATE TABLE IF NOT EXISTS envers_audit.user_audit
(
    id VARCHAR(255) NOT NULL,
    rev integer NOT NULL,
    revtype smallint,
    password VARCHAR(255),
    login VARCHAR(255),
    name VARCHAR(255),
    active BOOLEAN,
    CONSTRAINT user_audit_pkey PRIMARY KEY (id, rev),
    CONSTRAINT fkey_user_audit_revinfo_rev FOREIGN KEY (rev)
        REFERENCES envers_audit.revinfo (rev)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);